
name = "janwilmake_daily-interview"
main = "main.ts"
compatibility_date = "2025-01-22"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "daily-interview.uithub.com", custom_domain = true }
]

[triggers]
crons = [ "0 18 * * *" ]
#